import { defineSlotRecipe } from '@pandacss/dev';

const menuSlots = [
  'root',
  'trigger',
  'contextTrigger',
  'triggerItem',
  'indicator',
  'positioner',
  'content',
  'arrow',
  'arrowTip',
  'item',
  'itemText',
  'itemIndicator',
  'itemGroup',
  'itemGroupLabel',
  'separator',
] as const;

export const menuRecipe = defineSlotRecipe({
  className: 'menu',
  slots: menuSlots,
  base: {
    root: {
      display: 'contents',
    },
    trigger: {
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'center',
      gap: '2',
      minW: '0',
      h: '10',
      px: '4',
      bg: 'palette.background.surface',
      color: 'typography.color.body',
      fontSize: 'sm',
      fontWeight: 'medium',
      lineHeight: '1.2',
      borderWidth: '1px',
      borderStyle: 'solid',
      borderColor: 'palette.border',
      cursor: 'pointer',
      rounded: 'md',
      outline: '0px solid transparent',
      _focusVisible: {
        outlineWidth: '2px',
        outlineStyle: 'solid',
        outlineColor: { base: 'black', _dark: 'white' },
        borderColor: 'transparent',
      },
      transition: '0.1s all ease-in-out',
    },
    contextTrigger: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      minW: '60',
      minH: '48',
      px: '4',
      py: '3',
      color: 'typography.color.secondary',
      fontSize: 'sm',
      borderWidth: '1px',
      borderStyle: 'dashed',
      borderColor: 'palette.border.emphasized',
      rounded: 'md',
      userSelect: 'none',
      cursor: 'context-menu',
      outline: '0px solid transparent',
    },
    triggerItem: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: '2',
      minH: '9',
      px: '2',
      py: '1.5',
      cursor: 'pointer',
      color: 'typography.color.body',
      fontSize: 'sm',
      lineHeight: '1.3',
      rounded: 'sm',
      userSelect: 'none',
      outline: '0px solid transparent',
      _highlighted: {
        bg: 'palette.background.emphasized',
      },
      _focusVisible: {
        outlineWidth: '2px',
        outlineStyle: 'solid',
        outlineColor: 'palette.primary.focus',
        outlineOffset: '-2px',
      },
      _focus: {
        outlineWidth: '2px',
        outlineStyle: 'solid',
        outlineColor: 'palette.primary.focus',
        outlineOffset: '-2px',
      },
      '&[data-disabled]': {
        opacity: '0.6',
        cursor: 'not-allowed',
        color: 'typography.color.muted',
      },
      '&::after': {
        content: '"›"',
        color: 'typography.color.muted',
        fontSize: 'md',
        lineHeight: '1',
      },
    },
    indicator: {
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'center',
      color: 'typography.color.body',
      fontSize: 'sm',
      lineHeight: '0.2',
    },
    positioner: {
      zIndex: 'var(--z-index)',
    },
    content: {
      '--arrow-size': '10px',
      padding: '1',
      minW: '48',
      maxH: 'min(var(--available-height, 300px), 300px)',
      bg: 'palette.background.surface',
      borderWidth: '1px',
      borderStyle: 'solid',
      borderColor: 'palette.border',
      rounded: 'sm',
      boxShadow: 'md',
      overflowY: 'auto',
      outline: 'none',
      transformOrigin: 'var(--transform-origin)',
      zIndex: 'calc(1100 + var(--layer-index, 0))',
    },
    arrow: {
      '--arrow-size': '10px',
      '--arrow-background': 'var(--colors-palette-background-surface)',
      zIndex: '-1',
    },
    arrowTip: {
      borderTopWidth: '1px',
      borderLeftWidth: '1px',
      borderStyle: 'solid',
      borderColor: 'palette.border',
    },
    item: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: '2',
      minH: '9',
      px: '2',
      py: '1.5',
      cursor: 'pointer',
      color: 'typography.color.body', 
      fontSize: 'sm',
      lineHeight: '1.3',
      rounded: 'sm',
      userSelect: 'none',
      outline: '0px solid transparent',
      _hover: {
        bg: { base: 'blackAlpha.100', _dark: 'whiteAlpha.100' },
      },
      _highlighted: {
        bg: { base: 'blackAlpha.100', _dark: 'whiteAlpha.100' },
      },
      _focusVisible: {
        outlineWidth: '2px',
        outlineStyle: 'solid',
        outlineColor: 'palette.primary.focus',
        outlineOffset: '-2px',
      },
      '&[data-disabled]': {
        opacity: '0.6',
        cursor: 'not-allowed',
        color: 'typography.color.muted',
      },
    },
    itemText: {
      flex: '1',
      minW: '0',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
      whiteSpace: 'nowrap',
    },
    itemIndicator: {
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'center',
      flexShrink: '0',
      color: 'palette.primary.main',
      fontSize: 'sm',
    },
    itemGroup: {
      display: 'grid',
      gap: '0.5',
    },
    itemGroupLabel: {
      px: '2',
      pt: '1',
      pb: '0.5',
      fontSize: 'xs',
      color: 'typography.color.muted',
      textTransform: 'uppercase',
      letterSpacing: 'wide',
    },
    separator: {
      height: '1px',
      my: '1',
      border: 'none',
      bg: 'palette.border',
    },
  },
});
